# -*- coding: utf-8 -*-
"""Readme.MD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k13jCHpg53r1bu3yk6JVmpl8zbfOTx6S

**Machine Learning UAS**

*   [Laporan](https://github.com/wednesafa/UAS-Machine-Learning/blob/main/Laporan_Proyek_MachineLearning.ipynb)
*   [Code](https://github.com/wednesafa/UAS-Machine-Learning/blob/main/Copy_of_Dataset%20(2).ipynb)
"""